### ISSUE TITLE
 chaincodeClient.Query  illegal base64 data

### ISSUE THREAD

**Issue by allan-zhou** [arxanchain/tomago-sdk-go#5]
**报错信息**
```shell
2018/01/24 18:25:09 chaincodeClient.Query  illegal base64 data at input byte 74
```

**tomagoClient  配置信息**
```go
cryptoConfig := &restapi.CryptoConfig{
	Enable:         true,
	CertsStorePath: "./certs",
}

config := &restapi.Config{
	Address:   "http://192.168.1.185:9143",
	ApiKey:    "F8pxCN1Mp1516701344",
	CryptoCfg: cryptoConfig,
}

tomagoClient, err := tomagoapi.NewTomagoClient(config)
```
**原因推测：**
封装BlockchainClient时，请求的URL地址错误
```go
//  BlockchainClient源码中Query方法
r := t.c.NewRequest("POST", "/v2/blockchain/query")
```
对我而言，我实际需要请求的地址是 http://hostname:port/tomago/v2/blockchain/query

另外，目前&restapi.Config并不支持配置URL path的配置

**Comment by ewangplay** [comment]
首先非常感谢 @loopzhou 发现问题并提交了issue。

这个问题的修复涉及到SDK和服务端Wasabi的同时修改，我先提交一个修改方案， @Honghaohan2013 你测试一下这个方案是否OK？然后报告一下测试结果，如果这个修改方案可行，再正式提交release。

**Comment by Honghaohan2013** [comment]
@ewangplay 好的，我先根据这个方案在本地起个环境测试一下，测试ok之后再提交release

**Comment by ewangplay** [comment]
问题已经Fix，但需要服务端的wasabi服务升级到1.5.0版本，配合最新的SDK来使用。
